### ISSUE TITLE
start_date of get_price_history does not actually change anything

### ISSUE THREAD

**Issue by platypushunter** [areed1192/td-ameritrade-api#3]
I have this code to get a price history

```
start = int((time.time()*1000)-1)  # For some reason this value doesn't actually change the output?
end = int(time.time()*1000)

def get_prices(symbol=str):  # as the program goes on the list gets longer and longer. No idea why. Maybe ext hours?
     raw_prices = td_client.get_price_history(
          symbol=symbol,
          start_date=start,
          end_date=end,
          frequency_type='minute',
          frequency='1',
          extended_hours='True')
     prices = pd.DataFrame(data=raw_prices['candles'], columns=['close'])
     return prices
```

The start date does not affect the output. If i use SPY (a 24 hour stock) as the symbol it gets prices starting at 7 am today no matter what. I Figure this is a bug somewhere

**Comment by monsieur40a** [comment]
`# Grab the Price History, custom time frame.
price_history = price_history_service.get_price_history(
    symbol='SPY',
    frequency_type=FrequencyType.Minute,
    frequency=1,
    start_date=start_date,
    end_date=end_date,
    extended_hours_needed=True
)

import pandas as pd

# print(len(price_history['candles']))
# print(price_history['candles'][:10])

df = pd.DataFrame.from_records(price_history['candles'])
df.sort_values(by="datetime", ascending=True, inplace=True)
# print(df)

df["date"] = pd.to_datetime(df['datetime'], unit='ms')

print(df['date'].dt.normalize().value_counts().sort_index())

print(24*60)`

2022-04-06     727
2022-04-07     946
2022-04-08     863
2022-04-11    1048
2022-04-12    1027
2022-04-13     904
2022-04-14     879
2022-04-18     973
2022-04-19     965
2022-04-20     921
2022-04-21     896
2022-04-22     971
2022-04-25    1119
2022-04-26     980
2022-04-27    1093
2022-04-28    1012
2022-04-29     966
2022-05-02    1036
2022-05-03     984
2022-05-04     914
2022-05-05    1007
2022-05-06     972
Name: date, dtype: int64
1440

I was able to get it to work with the above code and output. Note it's possible to get 1440 1 min candles in 24 hours but SPY doesn't necessarily always have trades in that period.

**Comment by platypushunter** [comment]
It's been a long time since I've tried tackling this issue, but I think due to the fact that this project is being replaced by td-ameritrade-api, i think its safe to just say its a bug on my side somewhere, but I'm transitioning away from this project anyway, so it's not exactly a big problem.

**Comment by platypushunter** [comment]
It seems as if this issue is actually with the much older td-ameritrade-python api, which is what i have been referencing. I will consider this issue closed

**Comment by lightspeedsnail** [comment]
ya i feel the same it has to be more than a day diff between start and end
